[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'ASPNETCORE_URLS=http://+:$PORT dotnet Pandora.API.dll'"
healthcheckPath = "/swagger/index.html"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
